spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1870168452
    driver-class-name: com.mysql.cj.jdbc.Driver